name: GenerateDocumentation
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate the documentation
        run: .\docs\Create-Module-Documentation.ps1
        shell: powershell
